services:
  # <-- POSTGRES -->
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ufkunl
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5435:5432"
    networks:
      - postgres
    restart: unless-stopped
  # <-- KAFKA -->
  fd-kafka:
    image: spotify/kafka
    ports:
      - "2181:2181" #zookeper
      - "9092:9092" #kafka
    hostname: localhost
    container_name: kafka-container
    environment:
      - "ADVERTISED_HOST=localhost"
      - "ADVERTISED_PORT=9092"
      - "AUTO_CREATE_TOPICS=true" #spring boot tarafından topic create edilmesi için
    command: > #replication-factor: kaç kafka sunucusunda verinin yedeği olsun?
      bash -c
      "(sleep 15s &&
      /opt/kafka_2.11-0.10.1.0/bin/kafka-topics.sh
      --create
      --zookeeper
      localhost:2181 --replication-factor 1 --partitions 1
      --topic fd-topic &) && (supervisord -n)"

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
  pgadmin: