#spring.application.name=api-gateway
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
#server.port=8080
#
#logging.level.root=info
#logging.level.root.org.springframework.cloud.gateway.route.RouteDefinitionLocator=INFO
#logging.level.root.org.springframework.cloud.gateway=TRACE
#
#spring.cloud.gateway.routes[0].id=customer
#spring.cloud.gateway.routes[0].uri=http://localhost:8081
#spring.cloud.gateway.routes[0].predicates[0]=Path=/customer-service/**
#spring.cloud.gateway.routes[0].filters[0]=RewritePath=/customer-service/(?<segment>/?.*),$\{segment}
#
#spring.cloud.gateway.routes[1].id=fraud
#spring.cloud.gateway.routes[1].uri=lb://fraud/
#spring.cloud.gateway.routes[1].predicates[0]=Path=/fraud/**

server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: false
      routes:
        - id: fraud-service
          uri: lb://fraud-service
          predicates:
            - Path=/fraud/**
          filters:
            - RewritePath=/fraud(?<segment>/?.*), /${segment}
        - id: customer-service
          uri: lb://customer-service
          predicates:
              - Path=/customer/**
          filters:
              - RewritePath=/customer(?<segment>/?.*), /${segment}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


